public class ResponseWrapper {
    // public String Category;
    // public List<FieldData> Fields;
}

// public class FieldData {
//     public String customFieldCode;
//     public Integer customFieldLength;
//     public Integer customFieldPositionNo;
//     public Integer customFieldSeqNo;
//     public String customFieldText;
//     public String customFieldType;
//     public String effectiveDate;
//     public PreviousAnswer previousAnswer;
//     public Response response;
//     public Map<String, Object> settings;
//     public Boolean visible;
// }

// public class PreviousAnswer {
//     public String answerText;
// }

// public class Response {
//     public Integer customFieldSeqNo;
//     public String answerText;
// }
